# Generated by Django 4.1.7 on 2023-03-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField(verbose_name='Широта')),
                ('longitude', models.IntegerField(verbose_name='Долгота')),
                ('temperature', models.IntegerField(verbose_name='Температура')),
                ('data_and_time', models.DateTimeField(verbose_name='Дата и время')),
            ],
        ),
    ]
